server:
    port: 8101

spring:
    application:
        name: biz-learning-eureka-client

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://biz-learning-eureka-server:8001/eureka/
