server:
    port: 8701

spring:
    application:
        name: biz-learning-feign-service

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://biz-learning-eureka-server:8001/eureka/

feign:
    hystrix:
        enabled: true

logging:
    level:
        com.biz.cloud.service.UserFeignService: debug