server:
    port: 8701

spring:
    application:
        name: biz-learning-feign-service
    security:
        user:
            name: biz
            password: 123456

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@biz-learning-eureka-security-server:8001/eureka/

feign:
    hystrix:
        enabled: true

logging:
    level:
        com.biz.cloud.service.UserFeignService: debug