server:
    port: 8801

spring:
    application:
        name: biz-learning-zuul-proxy

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://biz-learning-eureka-server:8001/eureka/

zuul:
    prefix: /api #增加前缀
    sensitive-headers: Cookie,Set-Cookie,Authorization #配置过滤敏感的请求头信息，设置为空就不会过滤
    routes:
        biz-learning-user-service:
            path: /user-service/**
        biz-learning-feign-service:
            path: /feign-service/**
    ignored-services: biz-learning-user-service,biz-learning-feign-service #关闭默认配置

management:
    endpoints:
        web:
            exposure:
                include: 'routes'