server:
    port: 8801

spring:
    application:
        name: biz-learning-zuul-proxy
    security:
        user:
            name: biz
            password: 123456

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@biz-learning-eureka-security-server:8001/eureka/

zuul:
    prefix: /api #增加前缀
    routes:
        biz-learning-user-service:
            path: /user-service/**
        biz-learning-feign-service:
            path: /feign-service/**
    ignored-services: biz-learning-user-service,biz-learning-feign-service #关闭默认配置

management:
    endpoints:
        web:
            exposure:
                include: 'routes'