server:
    port: 8901

spring:
    application:
        name: biz-learning-config-server
    cloud:
        server:
            git:
                uri: https://github.com/donniewang/biz-learning.git
                clone-on-start: true

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://biz-learning-eureka-server:8001/eureka/